name = "backlog_defeater"
main = "src/index.ts"
compatibility_date = "2022-11-07"
nodejs_compat = true

[[ d1_databases ]]
binding = "DB"
database_name = "backlog-defeater-d1"
database_id = "YOUR DB ID"
migrations_dir = "drizzle"
